# llama.cpp server instantiation parameters
server_executable:
    Windows: "C:\\Users\\andrey.vukolov\\src\\llama.cpp\\llama-server.exe"
    Linux: "/home/twdragon/src/llama.cpp/build/bin/llama-server"
llm_dir:
    Windows: "F:\\twdragon\\src\\llama.cpp\\models"
    Linux: "/home/twdragon/src/llama.cpp/models"
# llm_filename: "Ministral-8B-Instruct-2410-Q4_K_L.gguf"
llm_filename: "Ministral-8B-Instruct-2410.Q5_K_M.gguf"
# llm_filename: "Mistral-Nemo-Instruct-2407.Q4_K_S.gguf"
llama_server_https: false
llama_server_host: "127.0.0.1"
llama_server_port: 8080
llama_server_generation_endpoint: "completion"
llama_server_tokenizer_endpoint: "tokenize"
llama_server_diagnostic_endpoint: "health"

# Tokenizer settings
window_width_coefficient: 0.6714
window_overlap_coefficient: 0.05
prediction_limit_coefficient: 0.4272

# Model settings
Ministral-8B-Instruct-2410.Q5_K_M:
    temperature: 0.75
    cache_prompt: false
    repeat_penalty: 1.09
    repeat_last_n: 24

Ministral-8B-Instruct-2410-Q4_K_L:
    temperature: 0.75
    cache_prompt: false
    repeat_penalty: 1.09
    repeat_last_n: 24

Mistral-Nemo-Instruct-2407.Q4_K_S:
    temperature: 0.3
    cache_prompt: false
    repeat_penalty: 1.1
    repeat_last_n: 24

Mistral-Nemo-Instruct-2407-Q4_K_M:
    temperature: 0.3
    cache_prompt: false
    repeat_penalty: 1.1
    repeat_last_n: 24

# Predefined prompts for presets
presets:
    - name: "Scientific meeting"
      cli_alias: "scientific-meeting"
      prompts: 
        - name: "Summary"
          text_before: |+
            System Prompt: Below is a fragment of a long meeting transcript. Please generate a detailed and comprehensive summary of this part of the discussion. Capture key ideas, arguments, numerical data, and supporting details without making assumptions or adding information. Do not use headings or footers, and do not mention anything about how the transcript was processed. Ensure the summary flows naturally, avoiding repetitive sentence structures or predictable openings such as "The discussion revolves around...". Instead, use varied sentence structures and transitions to create an engaging and seamless narrative. Format the summary as a single Markdown paragraph so it integrates seamlessly into the final summary.
            
            Transcript fragment:
            
          text_after: |+
            
            Response: 
            
        - name: "Key Insights"
          text_before: |+
            System Prompt: Below is the fragment of the long meeting transcript. Please generate a list of 2-3 main key insights for this part of the discussion, if there are any. Do not make any assumptions or add anything. Do not use any headings at the beginning or footers by the end of the list of the key insights. Prepare the list for being seamlessly integrated in the bigger final list of key insights. Format the list as a Markdown bulleted list.
            
            Transcript fragment:
            
          text_after: |+
            
            Response:
            
        - name: "Outline"
          text_before: |+
            System Prompt: Below is the fragment of the long meeting transcript. Please generate sequential and detailed outline of this part of the discussion. Pay attention to the key ideas, arguments, numerical data and supporting details, but without making assumptions or adding anything. Do not use any headings at the beginning or footers by the end of the outline. Prepare the outline for being seamlessly integrated in the bigger final outline. Format the outline as Markdown bulleted list.
            
            Transcript fragment:
            
          text_after: |+
            
            Response:
            
# =============================================================================
    - name: "Scientific meeting - detailed summary"
      cli_alias: "scientific-meeting-detailed-summary"
      prompts: 
        - name: "Summary"
          text_before: |+
            System Prompt: Below is a fragment of a long meeting transcript. Please retell this part of the discussion in very detailed, precise and comprehensive manner, without making assumptions or adding information. Do not use headings or footers, and do not mention anything about how the transcript was processed. Ensure the retelling flows naturally, avoiding repetitive sentence structures or predictable openings such as "The discussion revolves around...". Format your retelling as Markdown paragraphs so it integrates seamlessly into the final article.
            
            Transcript fragment:
            
          text_after: |+
            
            Response: 
            
        - name: "Key Insights"
          text_before: |+
            System Prompt: Below is the fragment of the long meeting transcript. Please generate a detailed list of 2-3 main key insights for this part of the discussion, if there are any. Do not make any assumptions or add anything. Do not use any headings at the beginning or footers by the end of the list of the key insights. Prepare the list for being seamlessly integrated in the bigger final list of key insights. Format the list as a Markdown bulleted list.
            
            Transcript fragment:
            
          text_after: |+
            
            Response:
            
        - name: "Outline"
          text_before: |+
            System Prompt: Below is the fragment of the long meeting transcript. Please generate sequential and detailed outline of this part of the discussion. Pay attention to the key ideas, arguments, numerical data and supporting details, but without making assumptions or adding anything. Do not use any headings at the beginning or footers by the end of the outline. Prepare the outline for being seamlessly integrated in the bigger final outline. Format the outline as Markdown bulleted list.
            
            Transcript fragment:
            
          text_after: |+
            
            Response:
            
# =============================================================================
    - name: "Scientific thesis"
      cli_alias: "scientific-thesis"
      prompts: 
        - name: "Compressed Summary"
          text_before: |+
            System Prompt: Below is the fragment of the long scientific thesis. Please rewrite this fragment in a compact but still detailed and comprehensive way, preserving all the key ideas, arguments, historical persons and events, dates, and supporting details. Avoid making assumptions or adding information. Do not use any headings at the beginning or footers by the end of the rewritten text. Focus on the text itself and do not explicitly mention anything about how the thesis was processed. Prepare the rewritten fragment for being seamlessly integrated into the bigger final text as a paragraph. Format your response as one Markdown paragraph.
            
            Fragment of the text:
            
          text_after: |+
            
            Response: 
            
        - name: "Key Insights"
          text_before: |+
            System Prompt: Below is the fragment of the long scientific thesis. Please generate a list of 2-3 main key insights for this part of the text, if there are any. Do not make any assumptions or add information. Do not use any headings at the beginning or footers by the end of the list of the key insights. Prepare the list for being seamlessly integrated in the bigger final list of key insights. Format the list as a Markdown bulleted list.
            
            Fragment of the text:
            
          text_after: |+
            
            Response:
            
        - name: "Outline"
          text_before: |+
            System Prompt: Below is the fragment of the long scientific thesis. Please generate concise, sequential and detailed outline of this fragment. Pay attention to the key ideas, arguments, historical persons and events, numerical data and supporting details, but without making assumptions or adding information. Do not use any headings at the beginning or footers by the end of the outline. Focus on the text itself and do not explicitly mention anything about how the thesis was processed. Prepare the outline for being seamlessly integrated in the bigger final outline. Format the outline as Markdown bulleted list.
            
            Fragment of the text:
            
          text_after: |+
            
            Response:
            
# =============================================================================
    - name: "Meeting summary only"
      cli_alias: "scientific-meeting-summary-only"
      prompts: 
        - name: "Summary"
          text_before: |+
            System Prompt: Below is a fragment of a long meeting transcript. Please generate a detailed and comprehensive summary of this part of the discussion. Capture key ideas, arguments, numerical data, and supporting details without making assumptions or adding information. Do not use headings or footers, and do not mention anything about how the transcript was processed. Ensure the summary flows naturally, avoiding repetitive sentence structures or predictable openings such as "The discussion revolves around...". Instead, use varied sentence structures and transitions to create an engaging and seamless narrative. Format the summary as a single Markdown paragraph so it integrates seamlessly into the final summary.
            
            Transcript fragment:
            
          text_after: |+
            
            Response: 
            
# =============================================================================
    - name: "Meeting retelling only"
      cli_alias: "scientific-meeting-retelling"
      prompts: 
        - name: "Retelling"
          text_before: |+
            System Prompt: Below is a fragment of a long meeting transcript. Please retell this part of the discussion in very detailed, precise and comprehensive manner, without making assumptions or adding information. Do not use headings or footers, and do not mention anything about how the transcript was processed. Ensure the retelling flows naturally, avoiding repetitive sentence structures or predictable openings such as "The discussion revolves around...". Format your retelling as Markdown paragraphs so it integrates seamlessly into the final article.
            
            Transcript fragment:
            
          text_after: |+
            
            Response: 
            
# =============================================================================

# [OPTIONAL] Whisper.cpp control section, requires only to recognize speech from video
whisper:
    ffmpeg:
        Windows: "C:\\Program Files\\ffmpeg\\bin\\ffmpeg.exe"
        Linux: "/util/ffmpeg/bin/ffmpeg"
    executable:
        Windows: "C:\\Users\\andrey.vukolov\\src\\whisper.cpp\\main.exe"
        Linux: "/home/twdragon/src/whisper.cpp/build/bin/whisper-cli"
    model_dir:
        Windows: "F:\\twdragon\\src\\whisper.cpp\\models\\large"
        # Windows: "F:\\twdragon\\src\\whisper.cpp\\models\\base"
        Linux: "/home/twdragon/src/whisper.cpp/models/large"
    model_filename: "ggml-large-v3.bin"
    # model_filename: "ggml-base.bin"
